import React from 'react';
import { Star, Quote, User, Building, Code, Rocket } from 'lucide-react';

const testimonials = [
  {
    name: 'Sarah Chen',
    role: 'Senior Full Stack Developer',
    avatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
    content: 'xBesh AI Creator has completely transformed how I approach development. What used to take me weeks now takes days. The AI-generated code is clean, efficient, and follows best practices perfectly.',
    rating: 5,
    icon: Code,
    gradient: 'from-purple-500 to-indigo-600'
  },
  {
    name: 'Marcus Rodriguez',
    role: 'CTO & Startup Founder',
    avatar: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
    content: 'Our development velocity increased by 300% after implementing xBesh. The automated testing and deployment features alone have saved us countless hours. This is the future of software development.',
    rating: 5,
    icon: Rocket,
    gradient: 'from-blue-500 to-cyan-600'
  },
  {
    name: 'Emily Watson',
    role: 'Lead Frontend Developer',
    avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
    content: 'The UI components generated by xBesh are pixel-perfect and responsive. I can focus on the creative aspects while the AI handles the repetitive coding tasks. It\'s like having a senior developer as my pair programming partner.',
    rating: 5,
    icon: User,
    gradient: 'from-pink-500 to-rose-600'
  },
  {
    name: 'David Kim',
    role: 'Engineering Manager',
    avatar: 'https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
    content: 'Managing a team of 15 developers, I needed a solution that could standardize our code quality and accelerate delivery. xBesh delivered beyond expectations. Our client satisfaction scores have never been higher.',
    rating: 5,
    icon: Building,
    gradient: 'from-emerald-500 to-teal-600'
  },
  {
    name: 'Lisa Thompson',
    role: 'Freelance Developer',
    avatar: 'https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
    content: 'As a freelancer, time is money. xBesh has allowed me to take on 40% more projects while delivering higher quality work. The ROI was immediate and substantial.',
    rating: 5,
    icon: Star,
    gradient: 'from-orange-500 to-red-600'
  },
  {
    name: 'Alex Johnson',
    role: 'Product Manager',
    avatar: 'https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
    content: 'From a product perspective, xBesh has been game-changing. We can iterate faster, test more ideas, and bring features to market in record time. Our development costs have dropped by 60%.',
    rating: 5,
    icon: Rocket,
    gradient: 'from-violet-500 to-purple-600'
  }
];

const TestimonialsSection = () => {
  return (
    <section className="py-32 bg-gradient-to-b from-gray-900 via-gray-950 to-gray-900 relative overflow-hidden">
      {/* Background Effects */}
      <div className="absolute inset-0">
        <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] from-blue-900/10 via-transparent to-transparent"></div>
        <div className="absolute top-1/3 left-1/4 w-96 h-96 bg-blue-500/5 rounded-full blur-3xl animate-pulse"></div>
        <div className="absolute bottom-1/3 right-1/4 w-96 h-96 bg-purple-500/5 rounded-full blur-3xl animate-pulse delay-1000"></div>
      </div>

      <div className="max-w-7xl mx-auto px-6 sm:px-8 lg:px-12 relative z-10">
        {/* Header */}
        <div className="text-center mb-20">
          <div className="inline-block mb-8">
            <div className="bg-gradient-to-r from-blue-500/10 to-purple-500/10 backdrop-blur-xl border border-blue-500/20 rounded-2xl px-8 py-4">
              <span className="text-blue-400 font-semibold text-sm tracking-wider uppercase">Testimonials</span>
            </div>
          </div>
          
          <h2 className="text-5xl md:text-7xl font-black text-white mb-8 leading-tight">
            Loved by
            <br />
            <span className="bg-gradient-to-r from-blue-400 via-purple-400 to-pink-400 bg-clip-text text-transparent">
              Thousands of Developers
            </span>
          </h2>
          
          <p className="text-xl md:text-2xl text-gray-300 max-w-4xl mx-auto leading-relaxed font-light">
            Join the community of developers who have transformed their workflow with xBesh AI Creator.
          </p>
        </div>

        {/* Stats Bar */}
        <div className="relative mb-20">
          <div className="absolute -inset-4 bg-gradient-to-r from-blue-600/10 via-purple-600/10 to-pink-600/10 rounded-3xl blur-xl"></div>
          <div className="relative bg-gray-800/30 backdrop-blur-2xl rounded-3xl p-8 border border-gray-700/30 shadow-2xl">
            <div className="grid grid-cols-1 md:grid-cols-4 gap-8 text-center">
              {[
                { value: '4.9/5', label: 'Average Rating', icon: Star },
                { value: '10,000+', label: 'Happy Developers', icon: User },
                { value: '50,000+', label: 'Projects Built', icon: Code },
                { value: '99.8%', label: 'Satisfaction Rate', icon: Building }
              ].map((stat, index) => {
                const IconComponent = stat.icon;
                return (
                  <div key={index} className="group">
                    <div className="flex items-center justify-center mb-4">
                      <div className="w-12 h-12 bg-gradient-to-r from-blue-500 to-purple-500 rounded-2xl flex items-center justify-center shadow-xl group-hover:scale-110 transition-transform duration-300">
                        <IconComponent className="w-6 h-6 text-white" />
                      </div>
                    </div>
                    <div className="text-3xl md:text-4xl font-black text-white mb-2 group-hover:scale-110 transition-transform duration-300">
                      {stat.value}
                    </div>
                    <div className="text-gray-300 font-medium">
                      {stat.label}
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </div>

        {/* Testimonials Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {testimonials.map((testimonial, index) => {
            const IconComponent = testimonial.icon;
            return (
              <div
                key={index}
                className="group relative"
              >
                {/* Glow Effect */}
                <div className={`absolute -inset-1 bg-gradient-to-r ${testimonial.gradient} rounded-3xl blur opacity-0 group-hover:opacity-20 transition duration-500`}></div>
                
                {/* Card */}
                <div className="relative bg-gray-800/50 backdrop-blur-xl rounded-3xl p-8 border border-gray-700/50 shadow-2xl transition-all duration-500 group-hover:scale-105 h-full flex flex-col">
                  {/* Quote Icon */}
                  <div className="flex justify-between items-start mb-6">
                    <Quote className="w-8 h-8 text-gray-400 opacity-50" />
                    <div className="flex space-x-1">
                      {[...Array(testimonial.rating)].map((_, i) => (
                        <Star key={i} className="w-5 h-5 text-yellow-400 fill-current" />
                      ))}
                    </div>
                  </div>
                  
                  {/* Content */}
                  <blockquote className="text-gray-300 leading-relaxed mb-8 flex-grow font-light text-lg">
                    "{testimonial.content}"
                  </blockquote>
                  
                  {/* Author */}
                  <div className="flex items-center space-x-4">
                    <div className="relative">
                      <div className={`absolute -inset-1 bg-gradient-to-r ${testimonial.gradient} rounded-full blur opacity-30`}></div>
                      <img
                        src={testimonial.avatar}
                        alt={testimonial.name}
                        className="relative w-14 h-14 rounded-full object-cover border-2 border-gray-600"
                      />
                    </div>
                    <div className="flex-grow">
                      <div className="font-semibold text-white text-lg">
                        {testimonial.name}
                      </div>
                      <div className="text-gray-400 text-sm">
                        {testimonial.role}
                      </div>
                    </div>
                    <div className={`w-10 h-10 bg-gradient-to-r ${testimonial.gradient} rounded-xl flex items-center justify-center shadow-lg group-hover:scale-110 transition-transform duration-300`}>
                      <IconComponent className="w-5 h-5 text-white" />
                    </div>
                  </div>
                </div>
              </div>
            );
          })}
        </div>

        {/* Trust Indicators */}
        <div className="mt-20 text-center">
          <div className="inline-flex items-center space-x-8 bg-gray-800/30 backdrop-blur-xl rounded-2xl px-12 py-6 border border-gray-700/30">
            <div className="flex items-center space-x-3">
              <div className="w-3 h-3 bg-green-400 rounded-full animate-pulse"></div>
              <span className="text-gray-300 font-medium">Trusted by developers worldwide</span>
            </div>
            <div className="w-px h-8 bg-gray-600"></div>
            <div className="flex items-center space-x-3">
              <Star className="w-5 h-5 text-yellow-400 fill-current" />
              <span className="text-gray-300 font-medium">4.9/5 on all platforms</span>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default TestimonialsSection;
